# Generated by Django 3.1.4 on 2021-10-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0006_pur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pur',
            name='product',
        ),
        migrations.AddField(
            model_name='pur',
            name='product',
            field=models.ManyToManyField(related_name='items', to='touqeerapp1.Product'),
        ),
    ]
