# Generated by Django 3.1.4 on 2021-10-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0008_auto_20211016_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pur',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
