# Generated by Django 3.1.4 on 2021-10-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0009_pur_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='Purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
