# Generated by Django 3.1.4 on 2021-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0012_auto_20211025_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
