# Generated by Django 3.1.4 on 2021-10-25 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('touqeerapp1', '0014_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sales',
            new_name='sale',
        ),
    ]
