# Generated by Django 3.1.4 on 2021-10-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0016_auto_20211025_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='touqeerapp1.sale'),
        ),
    ]
