# Generated by Django 3.1.4 on 2021-10-26 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('touqeerapp1', '0018_auto_20211025_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('quantity', models.IntegerField(null=True)),
                ('scheme', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('discountPercent', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('gst', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(related_name='productforsale', to='touqeerapp1.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin2', to=settings.AUTH_USER_MODEL),
        ),
    ]
