# Generated by Django 3.1.4 on 2021-10-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0019_auto_20211026_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='saleproduct',
        ),
    ]
