# Generated by Django 3.1.4 on 2021-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0020_auto_20211026_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='saleproduct',
            field=models.ManyToManyField(related_name='productforsale', to='touqeerapp1.SaleProduct'),
        ),
    ]
