# Generated by Django 3.1.4 on 2021-10-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0022_auto_20211026_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productName', to='touqeerapp1.product'),
        ),
    ]
