# Generated by Django 3.1.4 on 2021-10-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touqeerapp1', '0024_auto_20211101_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Area',
            field=models.ManyToManyField(to='touqeerapp1.Routes'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Area',
            field=models.ManyToManyField(to='touqeerapp1.Routes'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ManyToManyField(to='touqeerapp1.Employee'),
        ),
    ]
